### format new CIZ data to legacy DSF format

In [1]:
import pandas as pd

In [2]:
# this only covers columns from old crsp.dsf.

CIZ_TO_DSF = {
    "dlycaldt": "date",
    "dlyprc": "prc",
    "dlylow": "bidlo",
    "dlyhigh": "askhi",
    "dlyvol": "vol",
    "dlyret": "ret",
    "dlyretx": "retx",
    "dlybid": "bid",
    "dlyask": "ask",
    "dlycumfacpr": "cfacpr",
    "dlycumfacshr": "cfacshr",
    "dlyopen": "openprc",
    "dlynumtrd": "numtrd",
    # permno, permco, shrout are unchanged
}

In [3]:
list(CIZ_TO_DSF)

['dlycaldt',
 'dlyprc',
 'dlylow',
 'dlyhigh',
 'dlyvol',
 'dlyret',
 'dlyretx',
 'dlybid',
 'dlyask',
 'dlycumfacpr',
 'dlycumfacshr',
 'dlyopen',
 'dlynumtrd']

In [ ]:
path = "data/dsf/"
START_YEAR = 2010
END_YEAR = 2020
df_optimized = pd.read_parquet(
    path, 
    engine="pyarrow",
    columns=list(CIZ_TO_DSF),
    filters=[("year", ">=", START_YEAR), ("year", "<=", END_YEAR)]
)
df_optimized.head()

,dlycaldt,dlyprc,dlylow,dlyhigh,dlyvol,dlyret,dlyretx,dlybid,dlyask,dlycumfacpr,dlycumfacshr,dlyopen,dlynumtrd
0,2010-01-04,10.25,10.1,10.58,18500.0,-0.004854,-0.004854,10.21,10.26,1.0,1.0,10.58,<NA>
1,2010-01-04,3.1,2.75,3.28,27845.0,0.080139,0.080139,3.01,3.25,1.0,1.0,2.85,109
2,2010-01-04,39.56,38.0,39.76,33721.0,0.033438,0.033438,39.54,39.62,1.0,1.0,38.57,265
3,2010-01-04,40.2,39.75,40.55,47859.0,0.006006,0.006006,40.13,40.2,1.0,1.0,40.55,667
4,2010-01-04,1.4001,1.33,1.42,3900.0,-0.007021,-0.007021,1.4,1.42,1.0,1.0,1.4,<NA>

In [5]:
# after data
df_optimized = df_optimized.rename(columns=CIZ_TO_DSF)
df_optimized.head()

,date,prc,bidlo,askhi,vol,ret,retx,bid,ask,cfacpr,cfacshr,openprc,numtrd
0,2010-01-04,10.25,10.1,10.58,18500.0,-0.004854,-0.004854,10.21,10.26,1.0,1.0,10.58,<NA>
1,2010-01-04,3.1,2.75,3.28,27845.0,0.080139,0.080139,3.01,3.25,1.0,1.0,2.85,109
2,2010-01-04,39.56,38.0,39.76,33721.0,0.033438,0.033438,39.54,39.62,1.0,1.0,38.57,265
3,2010-01-04,40.2,39.75,40.55,47859.0,0.006006,0.006006,40.13,40.2,1.0,1.0,40.55,667
4,2010-01-04,1.4001,1.33,1.42,3900.0,-0.007021,-0.007021,1.4,1.42,1.0,1.0,1.4,<NA>

In [6]:
df_optimized['date'].dt.year.value_counts().sort_index()

date
2010    1011992
2011     973600
2012     932584
2013     918058
2014     938973
2015     950004
2016     923633
2017     902688
2018     901942
2019     906133
2020     912512
Name: count, dtype: int64